### ISSUE TITLE
Remaining items are not updating when we complete any task

### ISSUE THREAD

**Issue by saurabhhere** [kabirbaidhya/react-todo-app#21]
As we complete any task, no of remaining items remains same. Updating only when we add any task.

![Screenshot from 2020-10-20 01-20-02](https://user-images.githubusercontent.com/60233336/96504623-8f056800-1272-11eb-90a4-d464a02648a6.png)

**Comment by rakheesingh** [comment]
Hey @kabirbaidhya, I resolved the above bug in your todo app. Can you check and close this issue?
